name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          github_token: ${{ secrets.GITHUB_TOKEN }}
          enable_jekyll: false
          allow_empty_commit: false
      - run: pip install -r docs/requirements.txt
      - run: mkdocs gh-deploy --force --clean --verbose